/*
 * Copyright (C) 2014 De'vID jonpIn (David Yonge-Mallo)
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package org.tlhInganHol.android.klingonttsengine;

import android.content.Context;
import android.media.AudioFormat;
import android.media.MediaPlayer;
import android.speech.tts.SynthesisCallback;
import android.speech.tts.SynthesisRequest;
import android.speech.tts.TextToSpeech;
import android.speech.tts.TextToSpeechService;
import android.util.Log;

import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.Map;

/**
 * A text to speech engine that generates Klingon speech.
 * The engine supports two different Klingon voices.
 *
 * It exercises all aspects of the Text to speech engine API
 * {@link android.speech.tts.TextToSpeechService}.
 */
public class KlingonSpeakTtsService extends TextToSpeechService implements android.media.MediaPlayer.OnCompletionListener {
    private static final String TAG = "KlingonSpeakTtsService";

    // The media player object used to play the sounds.
    private MediaPlayer mMediaPlayer = null;

    private volatile String[] mCurrentLanguage = null;
    private volatile boolean mStopRequested = false;

    // This map contains the front half of full syllables.
    private static final Map<String, Integer> FRONT_HALF_SYLLABLE_TO_AUDIO_MAP;
    static {
        Map<String, Integer> initMap = new HashMap<String, Integer>();

        // THIS IS AUTOGENERATED CODE. DO NOT EDIT BELOW THIS LINE.
        // BEGIN: FRONT_HALF_SYLLABLE_TO_AUDIO_MAP
        initMap.put("bI-", R.raw.bi0);
        initMap.put("bo-", R.raw.bo0);
        initMap.put("Ce-", R.raw.ce0);
        initMap.put("CI-", R.raw.ci0);
        initMap.put("Co-", R.raw.co0);
        initMap.put("Cu-", R.raw.cu0);
        initMap.put("Da-", R.raw.da0);
        initMap.put("DI-", R.raw.di0);
        initMap.put("Do-", R.raw.do0);
        initMap.put("Du-", R.raw.du0);
        initMap.put("Go-", R.raw.go0);
        initMap.put("HI-", R.raw.hi0);
        initMap.put("jI-", R.raw.ji0);
        initMap.put("ju-", R.raw.ju0);
        initMap.put("lI-", R.raw.li0);
        initMap.put("lu-", R.raw.lu0);
        initMap.put("ma-", R.raw.ma0);
        initMap.put("mu-", R.raw.mu0);
        initMap.put("na-", R.raw.na0);
        initMap.put("nI-", R.raw.ni0);
        initMap.put("nu-", R.raw.nu0);
        initMap.put("pe-", R.raw.pe0);
        initMap.put("pI-", R.raw.pi0);
        initMap.put("qa-", R.raw.qa0);
        initMap.put("re-", R.raw.re0);
        initMap.put("Sa-", R.raw.sa0);
        initMap.put("Se-", R.raw.se0);
        initMap.put("Su-", R.raw.su0);
        initMap.put("te-", R.raw.te0);
        initMap.put("tI-", R.raw.ti0);
        initMap.put("tu-", R.raw.tu0);
        initMap.put("vI-", R.raw.vi0);
        initMap.put("wI-", R.raw.wi0);
        initMap.put("wo-", R.raw.wo0);
        initMap.put("xa-", R.raw.xa0);
        initMap.put("xI-", R.raw.xi0);
        initMap.put("ya-", R.raw.ya0);
        initMap.put("yI-", R.raw.yi0);
        initMap.put("za-", R.raw.za0);
        // END: FRONT_HALF_SYLLABLE_TO_AUDIO_MAP
        // THIS IS AUTOGENERATED CODE. DO NOT EDIT ABOVE THIS LINE.

        FRONT_HALF_SYLLABLE_TO_AUDIO_MAP = Collections.unmodifiableMap(initMap);
    }

    // This map contains short syllables, i.e., those of the form CV.
    // Unlike for the corresponding front half of a full syllable, the audio for a short syllable
    // doesn't end abruptly. For example, "Da-" (a front half syllable) is the prefix for "you-it",
    // whereas "Da" (a short syllable) is the verb for "behave as".
    private static final Map<String, Integer> SHORT_SYLLABLE_TO_AUDIO_MAP;
    static {
        Map<String, Integer> initMap = new HashMap<String, Integer>();
        // bo, cha, Da, DI, Do, gho, ghu, He, Hu, ja, je, jo, lu, po, QI, ra, ro, So, ta, tI, va, ya, yu, 'a, 'o

        // THIS IS AUTOGENERATED CODE. DO NOT EDIT BELOW THIS LINE.
        // BEGIN: SHORT_SYLLABLE_TO_AUDIO_MAP
        initMap.put("bo", R.raw.bo);
        initMap.put("Ca", R.raw.ca);
        initMap.put("Da", R.raw.da);
        initMap.put("DI", R.raw.di);
        initMap.put("Do", R.raw.do_);
        initMap.put("Go", R.raw.go);
        initMap.put("je", R.raw.je);
        initMap.put("ya", R.raw.ya);
        initMap.put("yu", R.raw.yu);
        initMap.put("za", R.raw.za);
        initMap.put("zo", R.raw.zo);
        // END: SHORT_SYLLABLE_TO_AUDIO_MAP
        // THIS IS AUTOGENERATED CODE. DO NOT EDIT ABOVE THIS LINE.

        SHORT_SYLLABLE_TO_AUDIO_MAP = Collections.unmodifiableMap(initMap);
    }

    // This map contains the back half of full syllables. It is preferable to avoid constructing
    // syllables by concatenating the front and back parts, as there is a noticeable discontinuity
    // in the audio if the vowel sound is not perfectly matched.
    private static final Map<String, Integer> BACK_HALF_SYLLABLE_TO_AUDIO_MAP;
    static {
        Map<String, Integer> initMap = new HashMap<String, Integer>();
        // -a, -e, -I, -o, -u

        BACK_HALF_SYLLABLE_TO_AUDIO_MAP = Collections.unmodifiableMap(initMap);
    }

    // This map contains full syllables, i.e., those of the form CVC, CVrgh, or CV[wy]'.
    private static final Map<String, Integer> MAIN_SYLLABLE_TO_AUDIO_MAP;
    static {
        Map<String, Integer> initMap = new HashMap<String, Integer>();

        // THIS IS AUTOGENERATED CODE. DO NOT EDIT BELOW THIS LINE.
        // BEGIN: MAIN_SYLLABLE_TO_AUDIO_MAP
        initMap.put("baC", R.raw.bac);
        initMap.put("baF", R.raw.baf);
        initMap.put("baG", R.raw.bag);
        initMap.put("baH", R.raw.bah);
        initMap.put("baj", R.raw.baj);
        initMap.put("baQ", R.raw.bak);
        initMap.put("bal", R.raw.bal);
        initMap.put("bam", R.raw.bam);
        initMap.put("baq", R.raw.baq);
        initMap.put("bar", R.raw.bar);
        initMap.put("barG", R.raw.barg);
        initMap.put("baS", R.raw.bas);
        initMap.put("bav", R.raw.bav);
        initMap.put("bax", R.raw.bax);
        initMap.put("baz", R.raw.baz);
        initMap.put("beb", R.raw.beb);
        initMap.put("beC", R.raw.bec);
        initMap.put("beG", R.raw.beg);
        initMap.put("beH", R.raw.beh);
        initMap.put("bej", R.raw.bej);
        initMap.put("beQ", R.raw.bek);
        initMap.put("bel", R.raw.bel);
        initMap.put("bem", R.raw.bem);
        initMap.put("ben", R.raw.ben);
        initMap.put("bep", R.raw.bep);
        initMap.put("beq", R.raw.beq);
        initMap.put("ber", R.raw.ber);
        initMap.put("berG", R.raw.berg);
        initMap.put("bet", R.raw.bet);
        initMap.put("bey", R.raw.bey);
        initMap.put("bez", R.raw.bez);
        initMap.put("bID", R.raw.bid);
        initMap.put("bIF", R.raw.bif);
        initMap.put("bIG", R.raw.big);
        initMap.put("bIH", R.raw.bih);
        initMap.put("bIj", R.raw.bij);
        initMap.put("bIQ", R.raw.bik);
        initMap.put("bIl", R.raw.bil);
        initMap.put("bIm", R.raw.bim);
        initMap.put("bIp", R.raw.bip);
        initMap.put("bIr", R.raw.bir);
        initMap.put("bIS", R.raw.bis);
        initMap.put("bIt", R.raw.bit);
        initMap.put("bIv", R.raw.biv);
        initMap.put("bIz", R.raw.biz);
        initMap.put("bob", R.raw.bob);
        initMap.put("boC", R.raw.boc);
        initMap.put("boD", R.raw.bod);
        initMap.put("boF", R.raw.bof);
        initMap.put("boG", R.raw.bog);
        initMap.put("boH", R.raw.boh);
        initMap.put("boj", R.raw.boj);
        initMap.put("boQ", R.raw.bok);
        initMap.put("bol", R.raw.bol);
        initMap.put("bom", R.raw.bom);
        initMap.put("bop", R.raw.bop);
        initMap.put("boq", R.raw.boq);
        initMap.put("bor", R.raw.bor);
        initMap.put("boS", R.raw.bos);
        initMap.put("bot", R.raw.bot);
        initMap.put("bov", R.raw.bov);
        initMap.put("box", R.raw.box);
        initMap.put("buD", R.raw.bud);
        initMap.put("buQ", R.raw.buk);
        initMap.put("bup", R.raw.bup);
        initMap.put("buq", R.raw.buq);
        initMap.put("bur", R.raw.bur);
        initMap.put("burG", R.raw.burg);
        initMap.put("buS", R.raw.bus);
        initMap.put("buv", R.raw.buv);
        initMap.put("bux", R.raw.bux);
        initMap.put("buyz", R.raw.buyz);
        initMap.put("Cab", R.raw.cab);
        initMap.put("CaC", R.raw.cac);
        initMap.put("CaD", R.raw.cad);
        initMap.put("CaF", R.raw.caf);
        initMap.put("CaG", R.raw.cag);
        initMap.put("CaH", R.raw.cah);
        initMap.put("Caj", R.raw.caj);
        initMap.put("CaQ", R.raw.cak);
        initMap.put("Cal", R.raw.cal);
        initMap.put("Cam", R.raw.cam);
        initMap.put("Can", R.raw.can);
        initMap.put("Cap", R.raw.cap);
        initMap.put("Caq", R.raw.caq);
        initMap.put("Car", R.raw.car);
        initMap.put("CarG", R.raw.carg);
        initMap.put("CaS", R.raw.cas);
        initMap.put("Cav", R.raw.cav);
        initMap.put("Cawz", R.raw.cawz);
        initMap.put("Cax", R.raw.cax);
        initMap.put("Cayz", R.raw.cayz);
        initMap.put("Caz", R.raw.caz);
        initMap.put("Ceb", R.raw.ceb);
        initMap.put("CeC", R.raw.cec);
        initMap.put("CeF", R.raw.cef);
        initMap.put("CeG", R.raw.ceg);
        initMap.put("CeH", R.raw.ceh);
        initMap.put("Cej", R.raw.cej);
        initMap.put("Cel", R.raw.cel);
        initMap.put("Cem", R.raw.cem);
        initMap.put("Cen", R.raw.cen);
        initMap.put("Cep", R.raw.cep);
        initMap.put("Cer", R.raw.cer);
        initMap.put("CerG", R.raw.cerg);
        initMap.put("CeS", R.raw.ces);
        initMap.put("Cet", R.raw.cet);
        initMap.put("Cev", R.raw.cev);
        initMap.put("Cez", R.raw.cez);
        initMap.put("CIC", R.raw.cic);
        initMap.put("CID", R.raw.cid);
        initMap.put("CIj", R.raw.cij);
        initMap.put("CIl", R.raw.cil);
        initMap.put("CIm", R.raw.cim);
        initMap.put("CIp", R.raw.cip);
        initMap.put("CIrG", R.raw.cirg);
        initMap.put("CIS", R.raw.cis);
        initMap.put("CIw", R.raw.ciw);
        initMap.put("Cob", R.raw.cob);
        initMap.put("CoF", R.raw.cof);
        initMap.put("CoG", R.raw.cog);
        initMap.put("CoH", R.raw.coh);
        initMap.put("CoQ", R.raw.cok);
        initMap.put("Col", R.raw.col);
        initMap.put("Com", R.raw.com);
        initMap.put("Con", R.raw.con);
        initMap.put("Cop", R.raw.cop);
        initMap.put("Coq", R.raw.coq);
        initMap.put("Cor", R.raw.cor);
        initMap.put("CorG", R.raw.corg);
        initMap.put("CoS", R.raw.cos);
        initMap.put("Cot", R.raw.cot);
        initMap.put("Cov", R.raw.cov);
        initMap.put("Coz", R.raw.coz);
        initMap.put("CuC", R.raw.cuc);
        initMap.put("CuD", R.raw.cud);
        initMap.put("CuF", R.raw.cuf);
        initMap.put("CuG", R.raw.cug);
        initMap.put("CuH", R.raw.cuh);
        initMap.put("Cun", R.raw.cun);
        initMap.put("Cup", R.raw.cup);
        initMap.put("Cuq", R.raw.cuq);
        initMap.put("CuS", R.raw.cus);
        initMap.put("Cut", R.raw.cut);
        initMap.put("Cuv", R.raw.cuv);
        initMap.put("Cuy", R.raw.cuy);
        initMap.put("Cuz", R.raw.cuz);
        initMap.put("Dab", R.raw.dab);
        initMap.put("DaC", R.raw.dac);
        initMap.put("DaG", R.raw.dag);
        initMap.put("DaH", R.raw.dah);
        initMap.put("Daj", R.raw.daj);
        initMap.put("DaQ", R.raw.dak);
        initMap.put("Dal", R.raw.dal);
        initMap.put("Dan", R.raw.dan);
        initMap.put("Dap", R.raw.dap);
        initMap.put("Daq", R.raw.daq);
        initMap.put("Dar", R.raw.dar);
        initMap.put("DarG", R.raw.darg);
        initMap.put("DaS", R.raw.das);
        initMap.put("Dat", R.raw.dat);
        initMap.put("Dav", R.raw.dav);
        initMap.put("Dawz", R.raw.dawz);
        initMap.put("Day", R.raw.day);
        initMap.put("Daz", R.raw.daz);
        initMap.put("Deb", R.raw.deb);
        initMap.put("DeC", R.raw.dec);
        initMap.put("DeG", R.raw.deg);
        initMap.put("DeH", R.raw.deh);
        initMap.put("Dej", R.raw.dej);
        initMap.put("DeQ", R.raw.dek);
        initMap.put("Del", R.raw.del);
        initMap.put("Den", R.raw.den);
        initMap.put("Dep", R.raw.dep);
        initMap.put("Deq", R.raw.deq);
        initMap.put("Der", R.raw.der);
        initMap.put("DeS", R.raw.des);
        initMap.put("Dev", R.raw.dev);
        initMap.put("Dez", R.raw.dez);
        initMap.put("DIb", R.raw.dib);
        initMap.put("DIC", R.raw.dic);
        initMap.put("DIF", R.raw.dif);
        initMap.put("DIG", R.raw.dig);
        initMap.put("DIj", R.raw.dij);
        initMap.put("DIl", R.raw.dil);
        initMap.put("DIn", R.raw.din);
        initMap.put("DIp", R.raw.dip);
        initMap.put("DIr", R.raw.dir);
        initMap.put("DIS", R.raw.dis);
        initMap.put("DIv", R.raw.div);
        initMap.put("DIz", R.raw.diz);
        initMap.put("DoC", R.raw.doc);
        initMap.put("DoD", R.raw.dod);
        initMap.put("DoG", R.raw.dog);
        initMap.put("DoH", R.raw.doh);
        initMap.put("Doj", R.raw.doj);
        initMap.put("DoQ", R.raw.dok);
        initMap.put("Dol", R.raw.dol);
        initMap.put("Dom", R.raw.dom);
        initMap.put("Don", R.raw.don);
        initMap.put("Dop", R.raw.dop);
        initMap.put("Doq", R.raw.doq);
        initMap.put("Dor", R.raw.dor);
        initMap.put("DoS", R.raw.dos);
        initMap.put("Dov", R.raw.dov);
        initMap.put("Dox", R.raw.dox);
        initMap.put("Doyz", R.raw.doyz);
        initMap.put("Doz", R.raw.doz);
        initMap.put("Duj", R.raw.duj);
        initMap.put("DuQ", R.raw.duk);
        initMap.put("Duz", R.raw.duz);
        initMap.put("FaG", R.raw.fag);
        initMap.put("Fan", R.raw.fan);
        initMap.put("FaS", R.raw.fas);
        initMap.put("Fuz", R.raw.fuz);
        initMap.put("Gab", R.raw.gab);
        initMap.put("GaC", R.raw.gac);
        initMap.put("GaF", R.raw.gaf);
        initMap.put("GaG", R.raw.gag);
        initMap.put("GaH", R.raw.gah);
        initMap.put("Gaj", R.raw.gaj);
        initMap.put("Gal", R.raw.gal);
        initMap.put("Gam", R.raw.gam);
        initMap.put("Gan", R.raw.gan);
        initMap.put("Gap", R.raw.gap);
        initMap.put("Gaq", R.raw.gaq);
        initMap.put("Gar", R.raw.gar);
        initMap.put("GarG", R.raw.garg);
        initMap.put("Gaw", R.raw.gaw);
        initMap.put("Gawz", R.raw.gawz);
        initMap.put("Gax", R.raw.gax);
        initMap.put("Gay", R.raw.gay);
        initMap.put("Gayz", R.raw.gayz);
        initMap.put("Gaz", R.raw.gaz);
        initMap.put("Geb", R.raw.geb);
        initMap.put("GeD", R.raw.ged);
        initMap.put("GeG", R.raw.geg);
        initMap.put("Gel", R.raw.gel);
        initMap.put("Gem", R.raw.gem);
        initMap.put("Ger", R.raw.ger);
        initMap.put("GeS", R.raw.ges);
        initMap.put("Get", R.raw.get);
        initMap.put("Gev", R.raw.gev);
        initMap.put("Gez", R.raw.gez);
        initMap.put("GIx", R.raw.gix);
        initMap.put("Gob", R.raw.gob);
        initMap.put("GoC", R.raw.goc);
        initMap.put("GoD", R.raw.god);
        initMap.put("GoF", R.raw.gof);
        initMap.put("GoG", R.raw.gog);
        initMap.put("GoH", R.raw.goh);
        initMap.put("Goj", R.raw.goj);
        initMap.put("GoQ", R.raw.gok);
        initMap.put("Gol", R.raw.gol);
        initMap.put("Gom", R.raw.gom);
        initMap.put("Gon", R.raw.gon);
        initMap.put("Gop", R.raw.gop);
        initMap.put("Goq", R.raw.goq);
        initMap.put("Gor", R.raw.gor);
        initMap.put("GorG", R.raw.gorg);
        initMap.put("GoS", R.raw.gos);
        initMap.put("Got", R.raw.got);
        initMap.put("Gov", R.raw.gov);
        initMap.put("Goz", R.raw.goz);
        initMap.put("GuF", R.raw.guf);
        initMap.put("Guz", R.raw.guz);
        initMap.put("Hab", R.raw.hab);
        initMap.put("HaC", R.raw.hac);
        initMap.put("HaD", R.raw.had);
        initMap.put("HaG", R.raw.hag);
        initMap.put("HaH", R.raw.hah);
        initMap.put("Haj", R.raw.haj);
        initMap.put("HaQ", R.raw.hak);
        initMap.put("Hal", R.raw.hal);
        initMap.put("Ham", R.raw.ham);
        initMap.put("Han", R.raw.han);
        initMap.put("Hap", R.raw.hap);
        initMap.put("Haq", R.raw.haq);
        initMap.put("Har", R.raw.har);
        initMap.put("HarG", R.raw.harg);
        initMap.put("HaS", R.raw.has);
        initMap.put("Hat", R.raw.hat);
        initMap.put("Hawz", R.raw.hawz);
        initMap.put("Hax", R.raw.hax);
        initMap.put("Hayz", R.raw.hayz);
        initMap.put("Haz", R.raw.haz);
        initMap.put("HeG", R.raw.heg);
        initMap.put("Hey", R.raw.hey);
        initMap.put("HIq", R.raw.hiq);
        initMap.put("HIv", R.raw.hiv);
        initMap.put("HoC", R.raw.hoc);
        initMap.put("HoH", R.raw.hoh);
        initMap.put("Hol", R.raw.hol);
        initMap.put("Hom", R.raw.hom);
        initMap.put("HoS", R.raw.hos);
        initMap.put("Hov", R.raw.hov);
        initMap.put("Hoz", R.raw.hoz);
        initMap.put("HuH", R.raw.huh);
        initMap.put("Hum", R.raw.hum);
        initMap.put("Hut", R.raw.hut);
        initMap.put("jaC", R.raw.jac);
        initMap.put("jaG", R.raw.jag);
        initMap.put("jaH", R.raw.jah);
        initMap.put("jaj", R.raw.jaj);
        initMap.put("jav", R.raw.jav);
        initMap.put("jax", R.raw.jax);
        initMap.put("jaz", R.raw.jaz);
        initMap.put("jeG", R.raw.jeg);
        initMap.put("jemS", R.raw.jems);
        initMap.put("jey", R.raw.jey);
        initMap.put("jez", R.raw.jez);
        initMap.put("jIb", R.raw.jib);
        initMap.put("jIH", R.raw.jih);
        initMap.put("jon", R.raw.jon);
        initMap.put("joq", R.raw.joq);
        initMap.put("juH", R.raw.juh);
        initMap.put("Qab", R.raw.kab);
        initMap.put("QaC", R.raw.kac);
        initMap.put("QaD", R.raw.kad);
        initMap.put("QaF", R.raw.kaf);
        initMap.put("QaG", R.raw.kag);
        initMap.put("QaH", R.raw.kah);
        initMap.put("Qaj", R.raw.kaj);
        initMap.put("QaQ", R.raw.kak);
        initMap.put("Qal", R.raw.kal);
        initMap.put("Qam", R.raw.kam);
        initMap.put("Qan", R.raw.kan);
        initMap.put("Qap", R.raw.kap);
        initMap.put("Qaq", R.raw.kaq);
        initMap.put("QaS", R.raw.kas);
        initMap.put("Qat", R.raw.kat);
        initMap.put("Qav", R.raw.kav);
        initMap.put("Qawz", R.raw.kawz);
        initMap.put("Qax", R.raw.kax);
        initMap.put("Qayz", R.raw.kayz);
        initMap.put("Qaz", R.raw.kaz);
        initMap.put("QIH", R.raw.kih);
        initMap.put("QIt", R.raw.kit);
        initMap.put("Qob", R.raw.kob);
        initMap.put("QoF", R.raw.kof);
        initMap.put("Qoy", R.raw.koy);
        initMap.put("Qoz", R.raw.koz);
        initMap.put("QuC", R.raw.kuc);
        initMap.put("Qun", R.raw.kun);
        initMap.put("Quv", R.raw.kuv);
        initMap.put("laH", R.raw.lah);
        initMap.put("laj", R.raw.laj);
        initMap.put("lan", R.raw.lan);
        initMap.put("larG", R.raw.larg);
        initMap.put("lawz", R.raw.lawz);
        initMap.put("lax", R.raw.lax);
        initMap.put("layz", R.raw.layz);
        initMap.put("laz", R.raw.laz);
        initMap.put("leF", R.raw.lef);
        initMap.put("leG", R.raw.leg);
        initMap.put("leH", R.raw.leh);
        initMap.put("lIj", R.raw.lij);
        initMap.put("lIS", R.raw.lis);
        initMap.put("lIz", R.raw.liz);
        initMap.put("lob", R.raw.lob);
        initMap.put("loC", R.raw.loc);
        initMap.put("loD", R.raw.lod);
        initMap.put("loG", R.raw.log);
        initMap.put("loH", R.raw.loh);
        initMap.put("loj", R.raw.loj);
        initMap.put("loQ", R.raw.lok);
        initMap.put("lol", R.raw.lol);
        initMap.put("lom", R.raw.lom);
        initMap.put("lon", R.raw.lon);
        initMap.put("lop", R.raw.lop);
        initMap.put("lor", R.raw.lor);
        initMap.put("loS", R.raw.los);
        initMap.put("lot", R.raw.lot);
        initMap.put("lox", R.raw.lox);
        initMap.put("loy", R.raw.loy);
        initMap.put("loz", R.raw.loz);
        initMap.put("luS", R.raw.lus);
        initMap.put("luz", R.raw.luz);
        initMap.put("maC", R.raw.mac);
        initMap.put("maH", R.raw.mah);
        initMap.put("maj", R.raw.maj);
        initMap.put("mayz", R.raw.mayz);
        initMap.put("maz", R.raw.maz);
        initMap.put("meH", R.raw.meh);
        initMap.put("mej", R.raw.mej);
        initMap.put("mev", R.raw.mev);
        initMap.put("mey", R.raw.mey);
        initMap.put("mIt", R.raw.mit);
        initMap.put("mIz", R.raw.miz);
        initMap.put("moH", R.raw.moh);
        initMap.put("moj", R.raw.moj);
        initMap.put("moz", R.raw.moz);
        initMap.put("muz", R.raw.muz);
        initMap.put("naj", R.raw.naj);
        initMap.put("naz", R.raw.naz);
        initMap.put("neH", R.raw.neh);
        initMap.put("neS", R.raw.nes);
        initMap.put("nex", R.raw.nex);
        initMap.put("nID", R.raw.nid);
        initMap.put("nIH", R.raw.nih);
        initMap.put("nIS", R.raw.nis);
        initMap.put("nob", R.raw.nob);
        initMap.put("noC", R.raw.noc);
        initMap.put("noD", R.raw.nod);
        initMap.put("noF", R.raw.nof);
        initMap.put("noG", R.raw.nog);
        initMap.put("noH", R.raw.noh);
        initMap.put("noj", R.raw.noj);
        initMap.put("nol", R.raw.nol);
        initMap.put("nom", R.raw.nom);
        initMap.put("non", R.raw.non);
        initMap.put("nop", R.raw.nop);
        initMap.put("norG", R.raw.norg);
        initMap.put("noS", R.raw.nos);
        initMap.put("not", R.raw.not);
        initMap.put("nov", R.raw.nov);
        initMap.put("nox", R.raw.nox);
        initMap.put("noz", R.raw.noz);
        initMap.put("nuq", R.raw.nuq);
        initMap.put("paG", R.raw.pag);
        initMap.put("paw", R.raw.paw);
        initMap.put("paz", R.raw.paz);
        initMap.put("peG", R.raw.peg);
        initMap.put("pem", R.raw.pem);
        initMap.put("pet", R.raw.pet);
        initMap.put("pIn", R.raw.pin);
        initMap.put("poF", R.raw.pof);
        initMap.put("poS", R.raw.pos);
        initMap.put("puC", R.raw.puc);
        initMap.put("puq", R.raw.puq);
        initMap.put("puS", R.raw.pus);
        initMap.put("puz", R.raw.puz);
        initMap.put("qab", R.raw.qab);
        initMap.put("qaD", R.raw.qad);
        initMap.put("qaF", R.raw.qaf);
        initMap.put("qarD", R.raw.qard);
        initMap.put("qaS", R.raw.qas);
        initMap.put("qaw", R.raw.qaw);
        initMap.put("qaz", R.raw.qaz);
        initMap.put("qem", R.raw.qem);
        initMap.put("qey", R.raw.qey);
        initMap.put("qIm", R.raw.qim);
        initMap.put("qIp", R.raw.qip);
        initMap.put("qIrq", R.raw.qirq);
        initMap.put("qoH", R.raw.qoh);
        initMap.put("qoj", R.raw.qoj);
        initMap.put("qoq", R.raw.qoq);
        initMap.put("qoS", R.raw.qos);
        initMap.put("qox", R.raw.qox);
        initMap.put("qul", R.raw.qul);
        initMap.put("quv", R.raw.quv);
        initMap.put("quz", R.raw.quz);
        initMap.put("raj", R.raw.raj);
        initMap.put("ram", R.raw.ram);
        initMap.put("raz", R.raw.raz);
        initMap.put("reG", R.raw.reg);
        initMap.put("reH", R.raw.reh);
        initMap.put("ruC", R.raw.ruc);
        initMap.put("rup", R.raw.rup);
        initMap.put("rur", R.raw.rur);
        initMap.put("Sab", R.raw.sab);
        initMap.put("SaC", R.raw.sac);
        initMap.put("SaD", R.raw.sad);
        initMap.put("SaG", R.raw.sag);
        initMap.put("SaH", R.raw.sah);
        initMap.put("Saj", R.raw.saj);
        initMap.put("SaQ", R.raw.sak);
        initMap.put("Sal", R.raw.sal);
        initMap.put("Sam", R.raw.sam);
        initMap.put("San", R.raw.san);
        initMap.put("Sap", R.raw.sap);
        initMap.put("Saq", R.raw.saq);
        initMap.put("Sar", R.raw.sar);
        initMap.put("SarG", R.raw.sarg);
        initMap.put("SaS", R.raw.sas);
        initMap.put("Saw", R.raw.saw);
        initMap.put("Sawz", R.raw.sawz);
        initMap.put("Sax", R.raw.sax);
        initMap.put("Sayz", R.raw.sayz);
        initMap.put("Saz", R.raw.saz);
        initMap.put("SeC", R.raw.sec);
        initMap.put("SeD", R.raw.sed);
        initMap.put("SeF", R.raw.sef);
        initMap.put("SeG", R.raw.seg);
        initMap.put("SeH", R.raw.seh);
        initMap.put("SeQ", R.raw.sek);
        initMap.put("Sen", R.raw.sen);
        initMap.put("Sep", R.raw.sep);
        initMap.put("Seq", R.raw.seq);
        initMap.put("Ser", R.raw.ser);
        initMap.put("SeS", R.raw.ses);
        initMap.put("Sev", R.raw.sev);
        initMap.put("Sey", R.raw.sey);
        initMap.put("Sez", R.raw.sez);
        initMap.put("SIQ", R.raw.sik);
        initMap.put("SoC", R.raw.soc);
        initMap.put("SoH", R.raw.soh);
        initMap.put("Soj", R.raw.soj);
        initMap.put("Sop", R.raw.sop);
        initMap.put("SoS", R.raw.sos);
        initMap.put("Sov", R.raw.sov);
        initMap.put("SuD", R.raw.sud);
        initMap.put("Suv", R.raw.suv);
        initMap.put("taH", R.raw.tah);
        initMap.put("taj", R.raw.taj);
        initMap.put("tar", R.raw.tar);
        initMap.put("tarG", R.raw.targ);
        initMap.put("tayz", R.raw.tayz);
        initMap.put("taz", R.raw.taz);
        initMap.put("teb", R.raw.teb);
        initMap.put("tIn", R.raw.tin);
        initMap.put("tIq", R.raw.tiq);
        initMap.put("tIv", R.raw.tiv);
        initMap.put("tIy", R.raw.tiy);
        initMap.put("toz", R.raw.toz);
        initMap.put("tuH", R.raw.tuh);
        initMap.put("tuj", R.raw.tuj);
        initMap.put("tup", R.raw.tup);
        initMap.put("turn", R.raw.turn);
        initMap.put("tuz", R.raw.tuz);
        initMap.put("vaD", R.raw.vad);
        initMap.put("vaG", R.raw.vag);
        initMap.put("vaj", R.raw.vaj);
        initMap.put("vam", R.raw.vam);
        initMap.put("van", R.raw.van);
        initMap.put("vav", R.raw.vav);
        initMap.put("vax", R.raw.vax);
        initMap.put("vayz", R.raw.vayz);
        initMap.put("veq", R.raw.veq);
        initMap.put("vex", R.raw.vex);
        initMap.put("vIH", R.raw.vih);
        initMap.put("vIp", R.raw.vip);
        initMap.put("vIS", R.raw.vis);
        initMap.put("vIz", R.raw.viz);
        initMap.put("voG", R.raw.vog);
        initMap.put("voz", R.raw.voz);
        initMap.put("waz", R.raw.waz);
        initMap.put("wej", R.raw.wej);
        initMap.put("wIj", R.raw.wij);
        initMap.put("wIz", R.raw.wiz);
        initMap.put("wob", R.raw.wob);
        initMap.put("woC", R.raw.woc);
        initMap.put("woD", R.raw.wod);
        initMap.put("woG", R.raw.wog);
        initMap.put("woH", R.raw.woh);
        initMap.put("woj", R.raw.woj);
        initMap.put("woQ", R.raw.wok);
        initMap.put("wom", R.raw.wom);
        initMap.put("wor", R.raw.wor);
        initMap.put("woS", R.raw.wos);
        initMap.put("wot", R.raw.wot);
        initMap.put("wov", R.raw.wov);
        initMap.put("woz", R.raw.woz);
        initMap.put("wuD", R.raw.wud);
        initMap.put("wuQ", R.raw.wuk);
        initMap.put("wun", R.raw.wun);
        initMap.put("wup", R.raw.wup);
        initMap.put("wuq", R.raw.wuq);
        initMap.put("wuS", R.raw.wus);
        initMap.put("wuv", R.raw.wuv);
        initMap.put("wux", R.raw.wux);
        initMap.put("xab", R.raw.xab);
        initMap.put("xaC", R.raw.xac);
        initMap.put("xaG", R.raw.xag);
        initMap.put("xaQ", R.raw.xak);
        initMap.put("xam", R.raw.xam);
        initMap.put("xap", R.raw.xap);
        initMap.put("xaq", R.raw.xaq);
        initMap.put("xarG", R.raw.xarg);
        initMap.put("xaS", R.raw.xas);
        initMap.put("xawz", R.raw.xawz);
        initMap.put("xax", R.raw.xax);
        initMap.put("xay", R.raw.xay);
        initMap.put("xeD", R.raw.xed);
        initMap.put("xeF", R.raw.xef);
        initMap.put("xeG", R.raw.xeg);
        initMap.put("xej", R.raw.xej);
        initMap.put("xep", R.raw.xep);
        initMap.put("xer", R.raw.xer);
        initMap.put("xev", R.raw.xev);
        initMap.put("xex", R.raw.xex);
        initMap.put("xez", R.raw.xez);
        initMap.put("xIb", R.raw.xib);
        initMap.put("xIC", R.raw.xic);
        initMap.put("xIF", R.raw.xif);
        initMap.put("xIH", R.raw.xih);
        initMap.put("xIj", R.raw.xij);
        initMap.put("xIl", R.raw.xil);
        initMap.put("xIm", R.raw.xim);
        initMap.put("xIn", R.raw.xin);
        initMap.put("xIq", R.raw.xiq);
        initMap.put("xIS", R.raw.xis);
        initMap.put("xIv", R.raw.xiv);
        initMap.put("xIz", R.raw.xiz);
        initMap.put("xuC", R.raw.xuc);
        initMap.put("xuD", R.raw.xud);
        initMap.put("xuH", R.raw.xuh);
        initMap.put("xuQ", R.raw.xuk);
        initMap.put("xup", R.raw.xup);
        initMap.put("xux", R.raw.xux);
        initMap.put("xuz", R.raw.xuz);
        initMap.put("yab", R.raw.yab);
        initMap.put("yaC", R.raw.yac);
        initMap.put("yaD", R.raw.yad);
        initMap.put("yaG", R.raw.yag);
        initMap.put("yaH", R.raw.yah);
        initMap.put("yaj", R.raw.yaj);
        initMap.put("yan", R.raw.yan);
        initMap.put("yap", R.raw.yap);
        initMap.put("yaS", R.raw.yas);
        initMap.put("yat", R.raw.yat);
        initMap.put("yav", R.raw.yav);
        initMap.put("yax", R.raw.yax);
        initMap.put("yay", R.raw.yay);
        initMap.put("yayz", R.raw.yayz);
        initMap.put("yeb", R.raw.yeb);
        initMap.put("yej", R.raw.yej);
        initMap.put("yem", R.raw.yem);
        initMap.put("yep", R.raw.yep);
        initMap.put("yeq", R.raw.yeq);
        initMap.put("yer", R.raw.yer);
        initMap.put("yev", R.raw.yev);
        initMap.put("yIb", R.raw.yib);
        initMap.put("yIC", R.raw.yic);
        initMap.put("yIH", R.raw.yih);
        initMap.put("yIQ", R.raw.yik);
        initMap.put("yIn", R.raw.yin);
        initMap.put("yIr", R.raw.yir);
        initMap.put("yIS", R.raw.yis);
        initMap.put("yIt", R.raw.yit);
        initMap.put("yIv", R.raw.yiv);
        initMap.put("yIz", R.raw.yiz);
        initMap.put("yob", R.raw.yob);
        initMap.put("yoD", R.raw.yod);
        initMap.put("yoF", R.raw.yof);
        initMap.put("yoH", R.raw.yoh);
        initMap.put("yoj", R.raw.yoj);
        initMap.put("yol", R.raw.yol);
        initMap.put("yon", R.raw.yon);
        initMap.put("yop", R.raw.yop);
        initMap.put("yoq", R.raw.yoq);
        initMap.put("yor", R.raw.yor);
        initMap.put("yoS", R.raw.yos);
        initMap.put("yot", R.raw.yot);
        initMap.put("yov", R.raw.yov);
        initMap.put("yox", R.raw.yox);
        initMap.put("yoy", R.raw.yoy);
        initMap.put("yoz", R.raw.yoz);
        initMap.put("yub", R.raw.yub);
        initMap.put("yuC", R.raw.yuc);
        initMap.put("yuD", R.raw.yud);
        initMap.put("yuQ", R.raw.yuk);
        initMap.put("yup", R.raw.yup);
        initMap.put("yur", R.raw.yur);
        initMap.put("yuv", R.raw.yuv);
        initMap.put("yuz", R.raw.yuz);
        initMap.put("zab", R.raw.zab);
        initMap.put("zaC", R.raw.zac);
        initMap.put("zaD", R.raw.zad);
        initMap.put("zaF", R.raw.zaf);
        initMap.put("zaG", R.raw.zag);
        initMap.put("zaH", R.raw.zah);
        initMap.put("zaj", R.raw.zaj);
        initMap.put("zaQ", R.raw.zak);
        initMap.put("zal", R.raw.zal);
        initMap.put("zam", R.raw.zam);
        initMap.put("zan", R.raw.zan);
        initMap.put("zap", R.raw.zap);
        initMap.put("zaq", R.raw.zaq);
        initMap.put("zar", R.raw.zar);
        initMap.put("zarG", R.raw.zarg);
        initMap.put("zaS", R.raw.zas);
        initMap.put("zat", R.raw.zat);
        initMap.put("zav", R.raw.zav);
        initMap.put("zaw", R.raw.zaw);
        initMap.put("zawz", R.raw.zawz);
        initMap.put("zax", R.raw.zax);
        initMap.put("zayz", R.raw.zayz);
        initMap.put("zaz", R.raw.zaz);
        initMap.put("zeb", R.raw.zeb);
        initMap.put("zeC", R.raw.zec);
        initMap.put("zeD", R.raw.zed);
        initMap.put("zeF", R.raw.zef);
        initMap.put("zeG", R.raw.zeg);
        initMap.put("zeH", R.raw.zeh);
        initMap.put("zej", R.raw.zej);
        initMap.put("zeQ", R.raw.zek);
        initMap.put("zel", R.raw.zel);
        initMap.put("zem", R.raw.zem);
        initMap.put("zep", R.raw.zep);
        initMap.put("zeq", R.raw.zeq);
        initMap.put("zer", R.raw.zer);
        initMap.put("zeS", R.raw.zes);
        initMap.put("zet", R.raw.zet);
        initMap.put("zev", R.raw.zev);
        initMap.put("zex", R.raw.zex);
        initMap.put("zey", R.raw.zey);
        initMap.put("zez", R.raw.zez);
        initMap.put("zIb", R.raw.zib);
        initMap.put("zIG", R.raw.zig);
        initMap.put("zIH", R.raw.zih);
        initMap.put("zIj", R.raw.zij);
        initMap.put("zIQ", R.raw.zik);
        initMap.put("zIl", R.raw.zil);
        initMap.put("zIm", R.raw.zim);
        initMap.put("zIn", R.raw.zin);
        initMap.put("zIp", R.raw.zip);
        initMap.put("zIq", R.raw.ziq);
        initMap.put("zIr", R.raw.zir);
        initMap.put("zIS", R.raw.zis);
        initMap.put("zIt", R.raw.zit);
        initMap.put("zIv", R.raw.ziv);
        initMap.put("zIw", R.raw.ziw);
        initMap.put("zIx", R.raw.zix);
        initMap.put("zIz", R.raw.ziz);
        initMap.put("zob", R.raw.zob);
        initMap.put("zoC", R.raw.zoc);
        initMap.put("zoD", R.raw.zod);
        initMap.put("zoF", R.raw.zof);
        initMap.put("zoG", R.raw.zog);
        initMap.put("zoH", R.raw.zoh);
        initMap.put("zoj", R.raw.zoj);
        initMap.put("zoQ", R.raw.zok);
        initMap.put("zol", R.raw.zol);
        initMap.put("zom", R.raw.zom);
        initMap.put("zop", R.raw.zop);
        initMap.put("zor", R.raw.zor);
        initMap.put("zoS", R.raw.zos);
        initMap.put("zov", R.raw.zov);
        initMap.put("zox", R.raw.zox);
        initMap.put("zoyz", R.raw.zoyz);
        initMap.put("zoz", R.raw.zoz);
        initMap.put("zuC", R.raw.zuc);
        initMap.put("zuD", R.raw.zud);
        initMap.put("zuG", R.raw.zug);
        initMap.put("zuH", R.raw.zuh);
        initMap.put("zuj", R.raw.zuj);
        initMap.put("zuQ", R.raw.zuk);
        initMap.put("zul", R.raw.zul);
        initMap.put("zum", R.raw.zum);
        initMap.put("zun", R.raw.zun);
        initMap.put("zup", R.raw.zup);
        initMap.put("zur", R.raw.zur);
        initMap.put("zuS", R.raw.zus);
        initMap.put("zut", R.raw.zut);
        initMap.put("zux", R.raw.zux);
        initMap.put("zuy", R.raw.zuy);
        initMap.put("zuyz", R.raw.zuyz);
        initMap.put("zuz", R.raw.zuz);
        // END: MAIN_SYLLABLE_TO_AUDIO_MAP
        // THIS IS AUTOGENERATED CODE. DO NOT EDIT ABOVE THIS LINE.

        MAIN_SYLLABLE_TO_AUDIO_MAP = Collections.unmodifiableMap(initMap);
    }

    @Override
    public void onCreate() {
        super.onCreate();
        // We load the default language when we start up. This isn't strictly
        // required though, it can always be loaded lazily on the first call to
        // onLoadLanguage or onSynthesizeText. This a tradeoff between memory usage
        // and the latency of the first call.
        onLoadLanguage("tlh", "CAN", "");
    }

    @Override
    public void onDestroy() {
        super.onDestroy();
    }

    @Override
    protected String[] onGetLanguage() {
        // Note that mCurrentLanguage is volatile because this can be called from
        // multiple threads.
        return mCurrentLanguage;
    }

    @Override
    protected int onIsLanguageAvailable(String lang, String country, String variant) {
        // The robot speak synthesizer supports only english.
        if ("tlh".equals(lang)) {
            // We support two specific klingon languages, the canadian klingon language
            // and the american klingon language.
            if ("USA".equals(country) || "CAN".equals(country)) {
                // If the engine supported a specific variant, we would have
                // something like.
                //
                // if ("android".equals(variant)) {
                //     return TextToSpeech.LANG_COUNTRY_VAR_AVAILABLE;
                // }
                return TextToSpeech.LANG_COUNTRY_AVAILABLE;
            }

            // We support the language, but not the country.
            return TextToSpeech.LANG_AVAILABLE;
        }

        return TextToSpeech.LANG_NOT_SUPPORTED;
    }

    /*
     * Note that this method is synchronized, as is onSynthesizeText because
     * onLoadLanguage can be called from multiple threads (while onSynthesizeText
     * is always called from a single thread only).
     */
    @Override
    protected synchronized int onLoadLanguage(String lang, String country, String variant) {
        final int isLanguageAvailable = onIsLanguageAvailable(lang, country, variant);

        if (isLanguageAvailable == TextToSpeech.LANG_NOT_SUPPORTED) {
            return isLanguageAvailable;
        }

        String loadCountry = country;
        if (isLanguageAvailable == TextToSpeech.LANG_AVAILABLE) {
            loadCountry = "USA";
        }

        // If we've already loaded the requested language, we can return early.
        if (mCurrentLanguage != null) {
            if (mCurrentLanguage[0].equals(lang) && mCurrentLanguage[1].equals(country)) {
                return isLanguageAvailable;
            }
        }

        mCurrentLanguage = new String[] { lang, loadCountry, "" };

        return isLanguageAvailable;
    }

    @Override
    protected void onStop() {
        mStopRequested = true;
    }

    // Helper method to prepare a MediaPlayer with the audio and add it to the
    // front of the play list. Preparing this way helps to reduce any audio gap.
    private void prependSyllableToList(Integer resId) {
        if (resId.intValue() != 0) {
            // Alternatively:
            //   MediaPlayer mp = new MediaPlayer();
            //   mp.setDataSource(filename);
            //   mp.prepare();
            MediaPlayer mp = MediaPlayer.create(this, resId.intValue());

            // Chain this MediaPlayer to the front of the existing one (if any).
            mp.setNextMediaPlayer(mMediaPlayer);
            mp.setOnCompletionListener(this);
            mMediaPlayer = mp;
        }
    }

    private void prependCoughToList() {
        prependSyllableToList(R.raw.cough);
    }

    @Override
    protected synchronized void onSynthesizeText(SynthesisRequest request,
            SynthesisCallback callback) {
        // Note that we call onLoadLanguage here since there is no guarantee
        // that there would have been a prior call to this function.
        int load = onLoadLanguage(request.getLanguage(), request.getCountry(),
                request.getVariant());

        // We might get requests for a language we don't support - in which case
        // we error out early before wasting too much time.
        if (load == TextToSpeech.LANG_NOT_SUPPORTED) {
            callback.error();
            return;
        }

        // At this point, we have loaded the language we need for synthesis and
        // it is guaranteed that we support it so we proceed with synthesis.

        // We construct a list of syllables to be played.
        String condensedText = condenseKlingonDiTrigraphs(request.getText());
        Log.d(TAG, "---\n");
        Log.d(TAG, "condensedText: \"" + condensedText + "\"");
        boolean isFinalSyllable = true;
        while (!condensedText.equals("")) {
            // Syllables in the main syllable map must have length 3 or 4 (CVC or CVCC).
            boolean foundMatch = false;
            for (int len = 3; len <= 4; len++) {
                if (condensedText.length() < len) {
                    // Remaining text is too short to have a complete syllable.
                    break;
                }
                String tail = condensedText.substring(condensedText.length() - len);
                Integer resId = MAIN_SYLLABLE_TO_AUDIO_MAP.get(tail);
                if (resId != null) {
                    prependSyllableToList(resId);
                    condensedText = condensedText.substring(0, condensedText.length() - len);

                    // The next match won't be the final syllable in a word.
                    isFinalSyllable = false;
                    foundMatch = true;
                    Log.d(TAG, "Matched tail: {" + tail + "}");
                    break;
                }
            }
            if (!foundMatch) {
                String syllable = removeTailSyllable(condensedText);
                if (!syllable.equals("")) {
                    condensedText = condensedText.substring(0, condensedText.length() - syllable.length());
                    String vowel = getSyllableVowel(syllable);
                    int vowelIndex = syllable.indexOf(vowel);

                    // Split the syllable into front and back.
                    String syllableBack = syllable.substring(vowelIndex);
                    String syllableFront = syllable.substring(0, vowelIndex + vowel.length());
                    Integer backResId = BACK_HALF_SYLLABLE_TO_AUDIO_MAP.get("-" + syllableBack);
                    Integer frontResId = FRONT_HALF_SYLLABLE_TO_AUDIO_MAP.get(syllableFront + "-");

                    // If the syllable is CV, then it is a short syllable. If it is CV-, then it is an unattached prefix.
                    boolean isShortSyllable = syllableBack.equals(vowel);
                    boolean isUnattachedPrefix = syllableBack.equals(vowel + "-");
                    Log.d(TAG, "Syllable: {" + syllable + "}");
                    Log.d(TAG, "Syllable front: {" + syllableFront + "}");
                    Log.d(TAG, "Syllable back: {" + syllableBack + "}");
                    Log.d(TAG, "Vowel: {" + vowel + "}");
                    Log.d(TAG, "isShortSyllable: {" + isShortSyllable + "}");
                    Log.d(TAG, "isUnattachedPrefix: {" + isUnattachedPrefix + "}");
                    Log.d(TAG, "isFinalSyllable: {" + isFinalSyllable + "}");
                    if (isShortSyllable && !isFinalSyllable || isUnattachedPrefix) {
                        // If it's a short syllable but not the final syllable, then truncate the vowel.
                        // This is either an attached prefix, part of a multisyllabic word, or a CV verb attached to a suffix.
                        // The audio for {bo-} takes precedence over the audio for {bo} if it's the beginning part of a word.
                        // Also treat unattached prefixes the same way.
                        if (frontResId != null) {
                            prependSyllableToList(frontResId);
                            Log.d(TAG, "Matched syllable: {" + syllableFront + "-}");
                        } else {
                            prependCoughToList();
                        }
                    } else {
                        // Either it's not short, or it's short and final. So play audio for the
                        // whole syllable.
                        Integer resId = null;
                        if (isShortSyllable) {
                            // Try to get audio of the full short syllable in the map of short syllables.
                            resId = SHORT_SYLLABLE_TO_AUDIO_MAP.get(syllable);
                        }
                        if (resId != null) {
                            // We have a full short syllable, so play it. Ex: {bo}.
                            prependSyllableToList(resId);
                            Log.d(TAG, "Matched syllable: {" + syllable + "}");
                        } else {
                            // If the syllable isn't short, or it is short and we've failed to get
                            // audio for the full short syllable, then add both the front and the
                            // back.
                            boolean coughed = false;
                            if (backResId != null) {
                                prependSyllableToList(backResId);
                            } else {
                                String backConsonants = syllableBack.substring(vowel.length());
                                if (backConsonants.length() == 1) {
                                  // This should be avoided, but if there is no choice, say the
                                  // consonant by itself. It won't sound smooth.
                                  prependSyllableToList(getResIdForFallbackChar(backConsonants.charAt(0)));
                                } else {
                                  // There was a consonant cluster (-rgh, -w', -y'), can't fake it.
                                  prependCoughToList();
                                  coughed = true;
                                }
                            }
                            if (frontResId != null) {
                                prependSyllableToList(frontResId);
                            } else if (!coughed) {
                                // Cough only once if both parts are missing.
                                prependCoughToList();
                            }
                            Log.d(TAG, "Matched syllable: {" + syllableFront + "-" + syllableBack + "}");
                        }
                    }

                    // Now the next match won't be the final syllable in a word.
                    isFinalSyllable = false;
                    foundMatch = true;
                }
            }
            if (!foundMatch) {
                // No match for a complete syllable. Use a fallback sound. This should be avoided if possible.
                char value = condensedText.charAt(condensedText.length() - 1);
                condensedText = condensedText.substring(0, condensedText.length() - 1);
                prependSyllableToList(getResIdForFallbackChar(value));
                Log.d(TAG, "Stripped char: \"" + value + "\"");

                // The next match will be considered the final syllable in a new word.
                isFinalSyllable = true;
            }
        }
        beginPlayback();

        // Alright, we're done with our synthesis - yay!
        callback.done();
    }

    private static boolean isSimpleVowel(char value) {
        final String aeIou = "aeIou";
        return aeIou.indexOf(value) != -1;
    }

    // Attempt to remove a syllable from the end of a given text and return it. Return empty string
    // if unsuccessful. Both input and output are in condensed format.
    private static String removeTailSyllable(String input) {
        // Syllables can have the following forms, where C is a consonant, and V is a vowel:
        //   CV
        //   CVC   (excluding {ow} and {uw})
        //   CVrgh
        //   CVw'  (excluding {ow'} and {uw'})
        //   CVy'
        // Log.d(TAG, "removeTailSyllable from: {" + input + "}");

        String remainingText = input;
        String tail = "";

        // Deal with the ending.
        if (remainingText.length() > 3 && remainingText.endsWith("wz")) {
            // Ends in {w'}. Peak at the preceding vowel.
            char value = remainingText.charAt(remainingText.length() - 3);
            if (value == 'o' || value == 'u') {
                // Drop the "w".
                tail = "z";
            } else {
                tail = "wz";
            }
            // Remove the "wz", but leave the vowel.
            remainingText = remainingText.substring(0, remainingText.length() - 2);
        } else if (remainingText.length() > 2 && remainingText.endsWith("w")) {
            // Ends in {w}. Peak at the preceding vowel.
            char value = remainingText.charAt(remainingText.length() - 2);
            if (value == 'o' || value == 'u') {
                // Drop the "w".
                tail = "";
            } else {
                tail = "w";
            }
            // Remove the "w", but leave the vowel.
            remainingText = remainingText.substring(0, remainingText.length() - 1);
        } else if (remainingText.length() > 3 && remainingText.endsWith("yz")) {
            // Ends in {y'}.
            tail = "yz";
            remainingText = remainingText.substring(0, remainingText.length() - 2);
        } else if (remainingText.length() > 3 && remainingText.endsWith("rG")) {
            // Ends in {rgh}.
            tail = "rG";
            remainingText = remainingText.substring(0, remainingText.length() - 2);
        } else if (remainingText.length() > 2 && !isSimpleVowel(remainingText.charAt(remainingText.length() - 1))) {
            // Ends in something other than a vowel. Assume it's a consonant, unless it's a space.
            tail = remainingText.substring(remainingText.length() - 1);
            if (tail.equals(" ")) {
                // Not a valid final consonant.
                return "";
            }
            remainingText = remainingText.substring(0, remainingText.length() - 1);
        }
        // Log.d(TAG, "After ending: {" + remainingText + " / " + tail + "}");

        // Look for the vowel.
        if (remainingText.length() < 2 ||
            !isSimpleVowel(remainingText.charAt(remainingText.length() - 1))) {
            // Failed to extract a syllable from the tail.
            return "";
        }
        tail = remainingText.substring(remainingText.length() - 1) + tail;
        remainingText = remainingText.substring(0, remainingText.length() - 1);
        // Log.d(TAG, "After middle: {" + remainingText + " / " + tail + "}");

        // Look for the initial consonant.
        if (remainingText.length() < 1 ||
            isSimpleVowel(remainingText.charAt(remainingText.length() - 1))) {
            // Also a failure.
            return "";
        }
        tail = remainingText.substring(remainingText.length() - 1) + tail;
        remainingText = remainingText.substring(0, remainingText.length() - 1);
        // Log.d(TAG, "After beginning: {" + remainingText + " / " + tail + "}");

        return tail;
    }

    private static String getSyllableVowel(String syllable) {
        // Given a legitimate Klingon syllable, return its (possibly complex) vowel.
        // Note that "ow" and "uw" are not possible.
        String[] possibleVowels = {"aw", "ew", "Iw", "ay", "ey", "Iy", "oy", "uy", "a", "e", "I", "o", "u"};
        for (int i = 0; i < possibleVowels.length; ++i) {
            if (syllable.indexOf(possibleVowels[i]) != -1) {
                return possibleVowels[i];
            }
        }
        return "";
    }

    private static int getResIdForFallbackChar(char value) {
        switch(value) {
          case 'a':
            return R.raw.a;
          case 'b':
            return R.raw.b;
          case 'C': // {ch}
            return R.raw.c;
          case 'D':
            return R.raw.d;
          case 'e':
            return R.raw.e;
          case 'G': // {gh}
            return R.raw.g;
          case 'H':
            return R.raw.h;
          case 'I':
            return R.raw.i;
          case 'j':
            return R.raw.j;
          case 'l':
            return R.raw.l;
          case 'm':
            return R.raw.m;
          case 'n':
            return R.raw.n;
          case 'F': // {ng}
            return R.raw.f;
          case 'o':
            return R.raw.o;
          case 'p':
            return R.raw.p;
          case 'q':
            return R.raw.q;
          case 'Q':
            return R.raw.k;
          case 'r':
            return R.raw.r;
          case 'S':
            return R.raw.s;
          case 't':
            return R.raw.t;
          case 'x': // {tlh}
            return R.raw.x;
          case 'u':
            return R.raw.u;
          case 'v':
            return R.raw.v;
          case 'w':
            return R.raw.w;
          case 'y':
            return R.raw.y;
          case 'z': // {'}
            return R.raw.z;
          case ' ':
            return R.raw.silence;
          default:
            // Note that 0 denotes an invalid resource ID in Android.
            return 0;
        }
    }

    /*
     * Condense {tlhIngan Hol} with a mapping that represents diagraphs and trigraphs as single characters.
     * Also replace {'} with "z" for ease of processing. The input is assumed to be proper Klingon orthography.
     */
    private static String condenseKlingonDiTrigraphs(String input) {
        return input.replaceAll("[^A-Za-z'\\-]+", " ")  // Strip all non-alphabetical characters (except {'} and "-").
                    .replaceAll("ch", "C")
                    .replaceAll("gh", "G")   // {gh} has to be done before {ng} so that {ngh} -> "nG" and not "Fh".
                    .replaceAll("ng", "F")
                    .replaceAll("tlh", "x")
                    .replaceAll("'", "z");
    }

    private void beginPlayback() {
        // Someone called onStop, end the current synthesis and return.
        // The mStopRequested variable will be reset at the beginning of the
        // next synthesis.
        //
        // In general, a call to onStop() should make a best effort attempt
        // to stop all processing for the *current* onSynthesizeText request (if
        // one is active).
        if (mStopRequested || mMediaPlayer == null) {
            return;
        }

        // This starts the chain of playback.
        mMediaPlayer.start();

        // It is important to set this to null here, since if onSynthesizeText
        // is called again, we don't want to chain the currently playing
        // syllables to the end of the new chain.
        mMediaPlayer = null;
    }

    public void onCompletion(MediaPlayer mp) {
        // Be sure to release the audio resources when playback is completed.
        // Log.d(TAG, "onCompletion called");
        // mp.reset();
        mp.release();
    }
}
